### ISSUE TITLE
Memory leak with CGEvent

### ISSUE THREAD

**Issue by roundhill** [Clipy/Magnet#14]
Hi! When using this library we've noticed some memory leaks related to a `CGEvent`. Not sure if it is just our usage of it, but it could be related to the event object being retained and never released here:

https://github.com/Clipy/Magnet/blob/master/Lib/Magnet/HotKeyCenter.swift#L111-L116

One solution that seems to have fixed it for me was to use `passUnretained` instead of `passRetained` here: https://github.com/Clipy/Magnet/blob/master/Lib/Magnet/HotKeyCenter.swift#L170. I'm not sure if that could have a negative impact, though.

Any insights are appreciated!

**Comment by Econa77** [comment]
@roundhill Sorry for the late reply. This problem was fixed in #19 

Thanks for the report and advice 👍
