### ISSUE TITLE
Unregister all hotkeys by default when the app terminates

### ISSUE THREAD

**Issue by sindresorhus** [Clipy/Magnet#18]
I can't think of any scenario where I wouldn't want the shortcuts to be unregistered. Could also be an option, but if so, I think it should still default to `true`.

I don't want this boilerplate in my code:

```swift
func applicationWillTerminate(_ aNotification: Notification) {
	HotKeyCenter.shared.unregisterAll()
}
```

**Comment by Econa77** [comment]
@sindresorhus Thanks for your suggestion👍Support this with #21
