### ISSUE TITLE
2.2.0 (or 2.1.1)?

### ISSUE THREAD

**Issue by mshibanami** [Clipy/Magnet#22]
The current version of Magnet is 2.1.0 that was released over half a year ago.
And this app has had 7 commits after that.
Do you have a plan to increase the version number?
(I hope so because the versioning with Git tags is quite useful for me who use Carthage.)

**Comment by Econa77** [comment]
@mshibanami Sorry for the delay released.
We released [v2.2.0](https://github.com/Clipy/Magnet/releases/tag/v2.2.0) 👍
