### ISSUE TITLE
macOS Siri press and hold style shortcut

### ISSUE THREAD

**Issue by mykebates** [Clipy/Magnet#5]
How difficult would it be to implement a press and hold concept like the latest macOS does by default to trigger Siri(hold option + space).

Where would be the proper place in the codebase to introduce this type of timer? I'd be happy to try my hand at it, but would love a pointer on a good starting point.

Thanks!

**Comment by Econa77** [comment]
@mykebates It is very difficult to capture the Space key pressed.

Magnet.framework supporting sandbox application.
But there is no way to capture the space key in the current situation sandbox environment.

Implementation in a non-sandbox environment include the following methods.
1. Turn on the accessibility at system setting.
2. Turn off Sandbox.
3. Capture space key down and up event with `CGEvent.tapCreate`
　- http://stackoverflow.com/a/31898592
4. Implement handling space key up/down and start timer.

**Comment by mykebates** [comment]
Thanks for the input @Econa77.
What about the same concept without using spacebar.

Example: press and hold Command + E

**Comment by Econa77** [comment]
@mykebates Sorry, no solution now.
Cannot get a non-modifier key is in a sandbox environment.

There is no problem to provide as an option for non-sandbox.
Please send PR if you have time 👍
