### ISSUE TITLE
Publish 3.3.0 Release

### ISSUE THREAD

**Issue by orchetect** [Clipy/Magnet#77]
Currently the library is not building when used as SPM 'up to next major version'. But it builds fine with master branch.

(Recent API changes in the Sauce 2.2.0 dependency are preventing Magnet 3.2.0 from building.)

We just need a Magnet 3.3.0 release and it should resolve this.

**Comment by Econa77** [comment]
@orchetect Thanks 👍 I just released [v3.3.0](https://github.com/Clipy/Magnet/releases/tag/v3.3.0).

Thank you for reporting.
